version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - API_BIND_ADDR=:8080
      - API_DSN=postgres://db/aero_db?sslmode=disable&user=postgres&password=qwerty
      - API_LOG_LEVEL=info
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=aero_db
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./dumps/dump-202206160937-1.sql:/docker-entrypoint-initdb.d/dump-202206160937-1.sql
    healthcheck:
      test: PGPASSWORD='qwerty' psql -U postgres aero_db --command='SELECT 1'
      interval: 1s
      timeout: 2s
      retries: 5

volumes:
  postgres_volume: